### ISSUE TITLE
Provide from_le_bytes/be_bytes / to_le_bytes/be_bytes

### ISSUE THREAD

**Issue by archseer** [alygin/fdec#10]
I'm trying to parse big endian encoded i192s that are using two's complement. It looks like I currently need to determine the sign bit, then manually convert the number from two's complement to an unsigned number?

**Comment by alygin** [comment]
@archseer, have a look at the [v0.3.0](https://github.com/alygin/fdec/releases/tag/v0.3.0) release and [new examples](https://github.com/alygin/fdec/blob/eefd30e192749c199e88dc8755a8966554ac23bd/examples/creation.rs#L75-L97).
I'm closing the issue. Feel free to reopen it if something doesn't work.
